
import os
try:
    from moviepy.editor import ImageClip, TextClip, CompositeVideoClip, ColorClip
except ImportError:
    print("Please run: pip install moviepy")
    exit()

def create_commercial_loop(image_path, title_text, sub_text, output_file):
    """
    Turns a static screenshot into a 6-second premium silent loop 
    with a slow zoom and professional text overlay.
    """
    w, h = 1080, 1080  # Square format is ideal for grid layouts
    duration = 6.0
    
    # 1. The "Ken Burns" Zoom Effect
    # We load the image at 120% scale so we can zoom out without black bars
    img = ImageClip(image_path).resize(height=int(h * 1.2))
    
    # Zoom out effect: Scales from 1.2 down to 1.0 over 6 seconds
    # Note: moviepy resize requires a function of time
    img = img.resize(lambda t: 1 + 0.2 * (1 - t / duration)).set_position('center').set_duration(duration)

    # 2. The Dark Overlay (Gradient at bottom for text readability)
    overlay = ColorClip(size=(w, 400), color=(0,0,0)).set_opacity(0.7)
    overlay = overlay.set_position(('center', 'bottom')).set_duration(duration)

    # 3. The Typography
    # (Requires ImageMagick. If not installed, it exports without text)
    try:
        # Main Title (e.g., "Social Autopilot")
        # Ensure size allows wrapping or fits width
        txt_title = (TextClip(title_text, fontsize=80, color='white', font='Arial-Bold', method='caption', size=(w-100, None))
                     .set_position(('center', h - 350))
                     .set_duration(duration)
                     .crossfadein(0.5))
        
        # Subtitle (e.g., "We post. You work.")
        txt_sub = (TextClip(sub_text, fontsize=45, color='#38bdf8', font='Arial', method='caption', size=(w-100, None))
                   .set_position(('center', h - 200))
                   .set_duration(duration)
                   .crossfadein(1.0))
        
        final_clip = CompositeVideoClip([img, overlay, txt_title, txt_sub], size=(w,h))
    except Exception as e:
        print(f"⚠️ Text generation failed (Check ImageMagick): {e}")
        final_clip = img # Fallback to just image

    # 4. Export to MP4
    final_clip.write_videofile(output_file, fps=24, codec='libx264', audio=False, preset='medium')
    print(f"✅ Generated: {output_file}")

# === RUN YOUR VIDEOS ===
# Add your specific screenshots here
features = [
    {"img": "assets/social.jpg", "title": "Social Autopilot", "sub": "Daily posts generated by your Brand DNA.", "out": "social_loop.mp4"},
    {"img": "assets/ads.jpg",    "title": "Ad Management",    "sub": "Leads for $20, not $100.",            "out": "ads_loop.mp4"},
]

if __name__ == "__main__":
    for f in features:
        if os.path.exists(f["img"]):
            create_commercial_loop(f["img"], f["title"], f["sub"], f["out"])
        else:
            print(f"❌ Missing file: {f['img']}")
