
CODE = """
# ==========================================
# TRADEFLOW AI LANDING PAGE (MISSION 32)
# ==========================================

TRADEFLOW_HTML = \"\"\"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TradeFlow AI | Stop Losing Jobs</title>
    <style>
        :root { --bg: #030712; --primary: #3b82f6; --text: #f8fafc; --surface: #1e293b; --border: #334155; }
        body { font-family: 'Inter', sans-serif; background: var(--bg); color: var(--text); margin: 0; line-height: 1.5; }
        .container { max-width: 1000px; margin: 0 auto; padding: 40px 20px; }
        .header { text-align: center; margin-bottom: 60px; padding-top: 40px; }
        h1 { font-size: 3.5rem; margin-bottom: 10px; background: linear-gradient(to right, #60a5fa, #c084fc); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-weight: 800; }
        .lead { font-size: 1.25rem; color: #94a3b8; margin-bottom: 40px; }
        .calc-box { background: var(--surface); padding: 40px; border-radius: 20px; border: 1px solid var(--border); max-width: 700px; margin: 0 auto 80px; box-shadow: 0 20px 60px rgba(0,0,0,0.5); }
        .calc-input { width: 100%; padding: 12px; background: #0f172a; border: 1px solid var(--border); color: white; border-radius: 8px; font-size: 16px; margin-top: 8px; box-sizing: border-box; }
        .result-box { text-align: center; background: #0f172a; padding: 20px; border-radius: 12px; margin-top: 20px; border: 1px solid rgba(239,68,68,0.3); }
        .btn { display: inline-block; padding: 18px 40px; background: var(--primary); color: white; text-decoration: none; border-radius: 12px; font-weight: 700; font-size: 1.2rem; margin-top: 20px;}
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 30px; }
        .card { position: relative; border-radius: 16px; overflow: hidden; aspect-ratio: 16/9; background: #111; border: 1px solid rgba(255,255,255,0.1); }
        .card img { width: 100%; height: 100%; object-fit: cover; animation: kenBurns 15s infinite alternate ease-in-out; }
        @keyframes kenBurns { from { transform: scale(1.0); } to { transform: scale(1.15); } }
        .overlay { position: absolute; bottom: 0; left: 0; right: 0; background: linear-gradient(to top, rgba(0,0,0,0.95), transparent); padding: 20px; }
        h3 { margin: 0; color: white; font-size: 1.25rem; }
        p { margin: 5px 0 0; color: #cbd5e1; font-size: 0.9rem; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div style="font-weight:800; color:white; margin-bottom:20px; font-size:1.2rem;">⚡ TradeFlow AI</div>
            <h1>Stop Losing Jobs.</h1>
            <p class="lead">He answers instantly. You send to voicemail. <br>He gets the $15k install. You get nothing.</p>
            <a href="https://calendly.com/aiserviceco/demo" class="btn">Get My (863) AI Number</a>
        </div>
        
        <script>
            // Calculator Logic Inline
        </script>
        <div class="calc-box">
            <h3 style="text-align: center; margin-top: 0; color: #fff; font-size:1.5rem;">💸 Your Lost Revenue</h3>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
                <div><label style="font-size: 14px; color: #94a3b8;">Missed Calls / Week</label><input type="number" id="calls" value="8" class="calc-input"></div>
                <div><label style="font-size: 14px; color: #94a3b8;">Avg. Job Value ($)</label><input type="number" id="val" value="450" class="calc-input"></div>
            </div>
            <div class="result-box">
                <h2 id="result" style="margin: 5px 0; color: #ef4444; font-size: 3rem; font-weight: 800;">$144,000 / yr</h2>
            </div>
            <script>
                const inp = document.querySelectorAll('input');
                function c() {
                    const l = document.getElementById('calls').value * 0.7 * document.getElementById('val').value * 52;
                    document.getElementById('result').innerText = "$" + l.toLocaleString() + " / yr";
                }
                inp.forEach(e => e.addEventListener('input', c));
                c();
            </script>
        </div>

        <div class="grid">
             <div class="card">
                <!-- Using absolute path in /root/assets -->
                <img src="/assets/generated/social.jpg" onerror="this.src='https://via.placeholder.com/800x450?text=Social+Autopilot'">
                <div class="overlay"><h3>Social Autopilot</h3><p>Daily posts generated by your Brand DNA.</p></div>
            </div>
             <div class="card">
                <img src="/assets/generated/ads.jpg" onerror="this.src='https://via.placeholder.com/800x450?text=Ad+Management'">
                <div class="overlay"><h3>Ad Management</h3><p>Leads for $20, not $100.</p></div>
            </div>
             <div class="card">
                <div style="width:100%; height:100%; display:flex; align-items:center; justify-content:center; font-size:4rem;">📞</div>
                <div class="overlay"><h3>AI Receptionist</h3><p>Never miss a lead again.</p></div>
            </div>
        </div>
    </div>
</body>
</html>
\"\"\"

@app.function(image=image)
@modal.web_endpoint(label="start")
def tradeflow_landing():
    from fastapi.responses import HTMLResponse
    return HTMLResponse(content=TRADEFLOW_HTML, status_code=200)

@app.function(image=image)
@modal.web_endpoint(label="assets")
def tradeflow_assets(path: str):
    from fastapi.responses import FileResponse
    # Serving /root/assets/generated/{path}
    # Security: In prod, validate path.
    return FileResponse(f"/root/assets/generated/{path}")
"""

with open("deploy.py", "a", encoding="utf-8") as f:
    f.write(CODE)
