import os
import psycopg2
from dotenv import load_dotenv

load_dotenv(".env")
# Password from context: 1vonN2C5s0jmiIjbn
# We manually construct the DB URL to ensure no parsing errors
# DB Host: db.rzcpfwkygdvoshtwxncs.supabase.co
# User: postgres
# Pass: 1vonN2C5s0jmiIjbn
# DB: postgres

DB_HOST = "db.rzcpfwkygdvoshtwxncs.supabase.co"
DB_PASS = "1vonN2C5s0jmiIjbn"

SQL_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS office_inventory (
        id bigint generated by default as identity primary key,
        item text not null unique,
        quantity integer default 0,
        updated_at timestamp with time zone default timezone('utc'::text, now())
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS office_tasks (
        id bigint generated by default as identity primary key,
        description text not null,
        status text default 'pending',
        created_at timestamp with time zone default timezone('utc'::text, now())
    );
    """,
    """
    ALTER TABLE office_inventory ENABLE ROW LEVEL SECURITY;
    """,
    """
    CREATE POLICY "Public Access Inv" ON office_inventory FOR ALL USING (true);
    """,
    """
    ALTER TABLE office_tasks ENABLE ROW LEVEL SECURITY;
    """,
    """
    CREATE POLICY "Public Access Task" ON office_tasks FOR ALL USING (true);
    """
]

def auto_fix():
    print("🛠️ Attempting Automatic DB Repair via Psycopg2...")
    
    # Try Port 5432 (Direct) and 6543 (Pooler)
    ports = [5432, 6543]
    
    conn = None
    for port in ports:
        print(f"🔌 Connecting to Port {port}...")
        try:
             conn = psycopg2.connect(
                host=DB_HOST,
                database="postgres",
                user="postgres",
                password=DB_PASS,
                port=port,
                connect_timeout=10
             )
             print(f"✅ Connected on Port {port}!")
             break
        except Exception as e:
            print(f"⚠️ Failed Port {port}: {e}")
            
    if not conn:
        print("❌ CRITICAL: Could not connect to Database on any port. Password might be wrong or IP blocked.")
        return

    try:
        cur = conn.cursor()
        for sql in SQL_STATEMENTS:
            try:
                cur.execute(sql)
                print(f"   - Executed SQL chunk.")
            except Exception as e:
                # Ignore "already exists" errors gracefully if needed, but IF NOT EXISTS handles it.
                # Policy creation might fail if exists
                if "already exists" in str(e):
                    print("   - (Skipped existing object)")
                    conn.rollback() # Logic error handling
                else:
                    print(f"   ❌ SQL Error: {e}")
                    conn.rollback()
                    # Continue attempting others? No, mostly sequential dependency.
                    # But policies depend on tables.
        
        conn.commit()
        print("✅ DB Repair Logic Completed.")
        
    except Exception as e:
        print(f"❌ Execution Error: {e}")
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    auto_fix()
