import os
from supabase import create_client
from dotenv import load_dotenv

# Load env vars
load_dotenv()
load_dotenv('.env.local')

url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or os.environ.get("SUPABASE_URL")
key = os.environ.get("NEXT_PUBLIC_SUPABASE_ANON_KEY") or os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not url or not key:
    print("❌ Error: Missing Supabase credentials in .env")
    exit(1)

supabase = create_client(url, key)

def setup_calendar_table():
    print(f"Connecting to Supabase: {url}")
    
    # SQL to create the table if it doesn't exist
    # Note: We can't execute raw SQL with the JS/Python client easily without RDBMS access or a function
    # But we can try to Select from it to see if it exists
    
    try:
        print("Checking if 'calendar_events' table exists...")
        response = supabase.table('calendar_events').select("*").limit(1).execute()
        print("✅ Table 'calendar_events' exists.")
        print(f"   Rows found: {len(response.data)}")
    except Exception as e:
        print(f"⚠️ Table check failed (likely doesn't exist): {e}")
        print("\nTo create this table, please run this SQL in your Supabase Dashboard SQL Editor:")
        print("-" * 50)
        print("""
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    attendees TEXT,
    status TEXT DEFAULT 'confirmed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access
CREATE POLICY "Enable read access for all users" ON calendar_events FOR SELECT USING (true);
        """)
        print("-" * 50)

if __name__ == "__main__":
    setup_calendar_table()
