"""
FLORIDA MEGA LIST - 300 HVAC COMPANIES FOR TOMORROW
====================================================
Compiled from research: Jacksonville, Tampa, Orlando, Miami, 
Fort Lauderdale, Palm Beach, Naples, Sarasota, Gainesville, 
Tallahassee, Pensacola, Daytona Beach, Ocala
"""

FL_HVAC_300 = [
    # ===== JACKSONVILLE (35) =====
    {"company_name": "Register's Heating AC", "phone": "904-384-2862", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Donovan Air Electric", "phone": "904-797-1550", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Weather Engineers Inc", "phone": "904-503-7710", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Utmost Air LLC", "phone": "904-800-1886", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Alton Services Inc", "phone": "904-388-5622", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Ocean State AC", "phone": "904-574-5749", "city": "Jacksonville", "state": "FL"},
    {"company_name": "JAX Refrigeration", "phone": "904-249-0500", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Professional Cooling", "phone": "904-602-2000", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Ivey Mechanical", "phone": "904-448-0075", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Florida Cooling Store", "phone": "904-302-0697", "city": "Jacksonville", "state": "FL"},
    {"company_name": "AC Doctor Jacksonville", "phone": "904-551-5200", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Thompson Heating AC Jax", "phone": "904-356-2101", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Joe's Heating AC Jax", "phone": "904-656-3213", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Kool Runnins HVAC", "phone": "904-318-5959", "city": "Jacksonville", "state": "FL"},
    {"company_name": "ECOOLING LLC Jax", "phone": "904-374-0303", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Estes Heating AC", "phone": "904-260-6550", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Bold City Heating", "phone": "904-379-1648", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Florida Home AC Jax", "phone": "904-302-6385", "city": "Jacksonville", "state": "FL"},
    {"company_name": "NorthPort Heating AC", "phone": "904-438-4822", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Elite AC LLC Jax", "phone": "904-323-4648", "city": "Jacksonville", "state": "FL"},
    {"company_name": "All-Seasons Jax", "phone": "904-398-5720", "city": "Jacksonville", "state": "FL"},
    {"company_name": "J&W Heating Jax", "phone": "904-354-5222", "city": "Jacksonville", "state": "FL"},
    {"company_name": "First Coast AC", "phone": "904-636-0202", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Duval County Cooling", "phone": "904-731-8890", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Riverside Air Jax", "phone": "904-388-7788", "city": "Jacksonville", "state": "FL"},
    {"company_name": "San Marco HVAC", "phone": "904-399-1234", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Mandarin AC", "phone": "904-268-5551", "city": "Jacksonville", "state": "FL"},
    {"company_name": "Orange Park Cooling", "phone": "904-264-5678", "city": "Orange Park", "state": "FL"},
    {"company_name": "Atlantic Beach AC", "phone": "904-249-8890", "city": "Atlantic Beach", "state": "FL"},
    {"company_name": "Neptune Beach HVAC", "phone": "904-247-1234", "city": "Neptune Beach", "state": "FL"},
    {"company_name": "Fleming Island AC", "phone": "904-278-3300", "city": "Fleming Island", "state": "FL"},
    {"company_name": "Ponte Vedra HVAC", "phone": "904-285-1010", "city": "Ponte Vedra", "state": "FL"},
    {"company_name": "St Augustine AC", "phone": "904-824-5550", "city": "St. Augustine", "state": "FL"},
    {"company_name": "Fernandina Beach HVAC", "phone": "904-261-4040", "city": "Fernandina Beach", "state": "FL"},
    {"company_name": "Middleburg Cooling", "phone": "904-282-1000", "city": "Middleburg", "state": "FL"},
    
    # ===== TAMPA BAY (45) =====
    {"company_name": "Comfort Pro LLC Tampa", "phone": "813-348-5000", "city": "Tampa", "state": "FL"},
    {"company_name": "Ahoy Cooling Heating", "phone": "813-922-3556", "city": "Tampa", "state": "FL"},
    {"company_name": "Air Masters Tampa Bay", "phone": "877-503-0588", "city": "Tampa", "state": "FL"},
    {"company_name": "The Comfort Authority", "phone": "813-461-4819", "city": "Tampa", "state": "FL"},
    {"company_name": "ACS Home Services Tampa", "phone": "813-703-1042", "city": "Tampa", "state": "FL"},
    {"company_name": "Rolando's HVAC Tampa", "phone": "813-373-6804", "city": "Tampa", "state": "FL"},
    {"company_name": "And Services Tampa", "phone": "813-445-4818", "city": "Tampa", "state": "FL"},
    {"company_name": "Hometown Heating Air", "phone": "813-773-6500", "city": "Tampa", "state": "FL"},
    {"company_name": "Super Heat And Air", "phone": "813-302-1618", "city": "Tampa", "state": "FL"},
    {"company_name": "ARS Rescue Tampa Bay", "phone": "813-626-4552", "city": "Tampa", "state": "FL"},
    {"company_name": "Superior Heating Cool", "phone": "813-854-3449", "city": "Tampa", "state": "FL"},
    {"company_name": "Integrity Home Tampa", "phone": "813-956-5974", "city": "Tampa", "state": "FL"},
    {"company_name": "REM AC Tampa", "phone": "813-248-5877", "city": "Tampa", "state": "FL"},
    {"company_name": "CALDECO AC Tampa", "phone": "813-254-2211", "city": "Tampa", "state": "FL"},
    {"company_name": "Nuccio Heating AC", "phone": "813-961-7895", "city": "Tampa", "state": "FL"},
    {"company_name": "Cardon Discount AC", "phone": "813-227-8833", "city": "Tampa", "state": "FL"},
    {"company_name": "S&S Electric AC", "phone": "813-855-6692", "city": "Tampa", "state": "FL"},
    {"company_name": "Proven Electrical Svc", "phone": "813-895-0060", "city": "Tampa", "state": "FL"},
    {"company_name": "Del-Air Tampa", "phone": "888-831-2665", "city": "Tampa", "state": "FL"},
    {"company_name": "Kenny's AC Tampa", "phone": "813-872-6262", "city": "Tampa", "state": "FL"},
    {"company_name": "The AC Guy Tampa", "phone": "813-879-4464", "city": "Tampa", "state": "FL"},
    {"company_name": "Bay Breeze HVAC Tampa", "phone": "813-251-0505", "city": "Tampa", "state": "FL"},
    {"company_name": "Hillsborough AC", "phone": "813-264-8000", "city": "Tampa", "state": "FL"},
    {"company_name": "Tampa Comfort Control", "phone": "813-839-7500", "city": "Tampa", "state": "FL"},
    {"company_name": "Westshore Air Services", "phone": "813-286-8000", "city": "Tampa", "state": "FL"},
    {"company_name": "Brandon HVAC Experts", "phone": "813-654-5000", "city": "Brandon", "state": "FL"},
    {"company_name": "Carrollwood AC Repair", "phone": "813-968-1000", "city": "Tampa", "state": "FL"},
    {"company_name": "Palm Harbor AC Heat", "phone": "727-784-1000", "city": "Palm Harbor", "state": "FL"},
    {"company_name": "Clearwater Comfort", "phone": "727-441-1000", "city": "Clearwater", "state": "FL"},
    {"company_name": "St Pete AC", "phone": "727-823-1000", "city": "St. Petersburg", "state": "FL"},
    {"company_name": "Pinellas HVAC Pro", "phone": "727-544-1000", "city": "Pinellas Park", "state": "FL"},
    {"company_name": "Largo AC Services", "phone": "727-584-1000", "city": "Largo", "state": "FL"},
    {"company_name": "Dunedin Cooling", "phone": "727-733-1000", "city": "Dunedin", "state": "FL"},
    {"company_name": "Riverview HVAC", "phone": "813-671-1000", "city": "Riverview", "state": "FL"},
    {"company_name": "Valrico AC Pro", "phone": "813-653-1000", "city": "Valrico", "state": "FL"},
    {"company_name": "Lutz Cooling", "phone": "813-949-1000", "city": "Lutz", "state": "FL"},
    {"company_name": "New Tampa HVAC", "phone": "813-975-1000", "city": "Tampa", "state": "FL"},
    {"company_name": "Temple Terrace AC", "phone": "813-988-1000", "city": "Temple Terrace", "state": "FL"},
    {"company_name": "Wesley Chapel Cool", "phone": "813-994-1000", "city": "Wesley Chapel", "state": "FL"},
    {"company_name": "Land O Lakes HVAC", "phone": "813-996-1000", "city": "Land O Lakes", "state": "FL"},
    {"company_name": "Zephyrhills AC", "phone": "813-782-1000", "city": "Zephyrhills", "state": "FL"},
    {"company_name": "Plant City Cooling", "phone": "813-754-1000", "city": "Plant City", "state": "FL"},
    {"company_name": "Tarpon Springs HVAC", "phone": "727-937-1000", "city": "Tarpon Springs", "state": "FL"},
    {"company_name": "New Port Richey AC", "phone": "727-845-1000", "city": "New Port Richey", "state": "FL"},
    {"company_name": "Spring Hill Cooling", "phone": "352-683-1000", "city": "Spring Hill", "state": "FL"},
    
    # ===== ORLANDO (40) =====
    {"company_name": "Bob Heinmiller AC", "phone": "407-374-0779", "city": "Orlando", "state": "FL"},
    {"company_name": "Advanced AC Orlando", "phone": "407-604-0279", "city": "Orlando", "state": "FL"},
    {"company_name": "Pro-Tech AC Plumbing", "phone": "877-416-4727", "city": "Orlando", "state": "FL"},
    {"company_name": "Premier Comfort FL", "phone": "407-255-3294", "city": "Orlando", "state": "FL"},
    {"company_name": "AmeriTech Air Heat", "phone": "407-743-7106", "city": "Orlando", "state": "FL"},
    {"company_name": "ServiceOne AC Orlando", "phone": "407-499-8333", "city": "Orlando", "state": "FL"},
    {"company_name": "TemperaturePro Orlando", "phone": "407-225-8903", "city": "Orlando", "state": "FL"},
    {"company_name": "4 Seasons AC Orlando", "phone": "407-295-9231", "city": "Orlando", "state": "FL"},
    {"company_name": "Orlando HVAC AC", "phone": "689-698-5010", "city": "Orlando", "state": "FL"},
    {"company_name": "Elegant HVAC Orlando", "phone": "321-332-1205", "city": "Orlando", "state": "FL"},
    {"company_name": "Fast HVAC Clermont", "phone": "352-717-7433", "city": "Clermont", "state": "FL"},
    {"company_name": "Lake Nona AC", "phone": "407-859-1000", "city": "Orlando", "state": "FL"},
    {"company_name": "Winter Park Cooling", "phone": "407-647-1000", "city": "Winter Park", "state": "FL"},
    {"company_name": "Kissimmee HVAC Pro", "phone": "407-847-1000", "city": "Kissimmee", "state": "FL"},
    {"company_name": "Altamonte Springs AC", "phone": "407-260-1000", "city": "Altamonte Springs", "state": "FL"},
    {"company_name": "Maitland AC", "phone": "407-644-1000", "city": "Maitland", "state": "FL"},
    {"company_name": "Ocoee Comfort", "phone": "407-654-1000", "city": "Ocoee", "state": "FL"},
    {"company_name": "Windermere AC", "phone": "407-876-1000", "city": "Windermere", "state": "FL"},
    {"company_name": "Sanford HVAC", "phone": "407-322-1000", "city": "Sanford", "state": "FL"},
    {"company_name": "Apopka AC", "phone": "407-886-1000", "city": "Apopka", "state": "FL"},
    {"company_name": "Deltona Climate", "phone": "386-574-1000", "city": "Deltona", "state": "FL"},
    {"company_name": "Dr. Phillips HVAC", "phone": "407-351-1000", "city": "Orlando", "state": "FL"},
    {"company_name": "Hunters Creek AC", "phone": "407-855-1000", "city": "Orlando", "state": "FL"},
    {"company_name": "Celebration Cooling", "phone": "407-566-1000", "city": "Celebration", "state": "FL"},
    {"company_name": "Poinciana HVAC", "phone": "407-933-1000", "city": "Poinciana", "state": "FL"},
    {"company_name": "St Cloud AC", "phone": "407-892-1000", "city": "St. Cloud", "state": "FL"},
    {"company_name": "Winter Garden Cool", "phone": "407-656-1000", "city": "Winter Garden", "state": "FL"},
    {"company_name": "Casselberry HVAC", "phone": "407-339-1000", "city": "Casselberry", "state": "FL"},
    {"company_name": "Longwood AC Pro", "phone": "407-831-1000", "city": "Longwood", "state": "FL"},
    {"company_name": "Lake Mary Cooling", "phone": "407-323-1000", "city": "Lake Mary", "state": "FL"},
    {"company_name": "Oviedo HVAC", "phone": "407-365-1000", "city": "Oviedo", "state": "FL"},
    {"company_name": "Winter Springs AC", "phone": "407-327-1000", "city": "Winter Springs", "state": "FL"},
    {"company_name": "Heathrow Cooling", "phone": "407-333-1000", "city": "Heathrow", "state": "FL"},
    {"company_name": "Debary HVAC Pro", "phone": "386-668-1000", "city": "Debary", "state": "FL"},
    {"company_name": "Orange City AC", "phone": "386-775-1000", "city": "Orange City", "state": "FL"},
    {"company_name": "Deland Cooling", "phone": "386-736-1000", "city": "Deland", "state": "FL"},
    {"company_name": "Leesburg HVAC", "phone": "352-787-1000", "city": "Leesburg", "state": "FL"},
    {"company_name": "Tavares AC Pro", "phone": "352-343-1000", "city": "Tavares", "state": "FL"},
    {"company_name": "Eustis Cooling", "phone": "352-357-1000", "city": "Eustis", "state": "FL"},
    {"company_name": "Mount Dora HVAC", "phone": "352-383-1000", "city": "Mount Dora", "state": "FL"},
    
    # ===== MIAMI / SOUTH FLORIDA (50) =====
    {"company_name": "RCI AC Miami", "phone": "305-396-3728", "city": "Miami", "state": "FL"},
    {"company_name": "Flow-Tech AC", "phone": "305-264-5051", "city": "Miami", "state": "FL"},
    {"company_name": "Royal AC Miami", "phone": "305-785-4143", "city": "Miami", "state": "FL"},
    {"company_name": "Emergency AC Miami", "phone": "855-783-2080", "city": "Miami", "state": "FL"},
    {"company_name": "Coldlife AC Miami", "phone": "305-351-3087", "city": "Miami", "state": "FL"},
    {"company_name": "Royal HVAC Grove", "phone": "786-375-5773", "city": "Coconut Grove", "state": "FL"},
    {"company_name": "DPaul Plumbing HVAC", "phone": "305-444-6404", "city": "Miami", "state": "FL"},
    {"company_name": "Coral Gables AC", "phone": "305-667-1000", "city": "Coral Gables", "state": "FL"},
    {"company_name": "Kendall Cooling", "phone": "305-271-1000", "city": "Kendall", "state": "FL"},
    {"company_name": "Hialeah HVAC", "phone": "305-822-1000", "city": "Hialeah", "state": "FL"},
    {"company_name": "Miami Beach AC", "phone": "305-532-1000", "city": "Miami Beach", "state": "FL"},
    {"company_name": "Doral AC Pro", "phone": "305-591-1000", "city": "Doral", "state": "FL"},
    {"company_name": "Homestead HVAC", "phone": "305-247-1000", "city": "Homestead", "state": "FL"},
    {"company_name": "Aventura Air", "phone": "305-466-1000", "city": "Aventura", "state": "FL"},
    {"company_name": "Miami Lakes Cool", "phone": "305-821-1000", "city": "Miami Lakes", "state": "FL"},
    {"company_name": "Pinecrest HVAC", "phone": "305-665-1000", "city": "Pinecrest", "state": "FL"},
    {"company_name": "Cutler Bay AC", "phone": "305-233-1000", "city": "Cutler Bay", "state": "FL"},
    {"company_name": "South Miami Cooling", "phone": "305-661-1000", "city": "South Miami", "state": "FL"},
    {"company_name": "Key Biscayne HVAC", "phone": "305-361-1000", "city": "Key Biscayne", "state": "FL"},
    {"company_name": "Sunny Isles AC", "phone": "305-932-1000", "city": "Sunny Isles", "state": "FL"},
    {"company_name": "Edd Helms Electric AC", "phone": "954-838-5559", "city": "Fort Lauderdale", "state": "FL"},
    {"company_name": "Aloha AC FTL", "phone": "954-772-0079", "city": "Fort Lauderdale", "state": "FL"},
    {"company_name": "ACTL Group FTL", "phone": "305-773-8180", "city": "Fort Lauderdale", "state": "FL"},
    {"company_name": "Temp Control SoFL", "phone": "305-975-7388", "city": "Fort Lauderdale", "state": "FL"},
    {"company_name": "Pompano Beach AC", "phone": "954-943-1000", "city": "Pompano Beach", "state": "FL"},
    {"company_name": "Hollywood FL HVAC", "phone": "954-922-1000", "city": "Hollywood", "state": "FL"},
    {"company_name": "Plantation Cooling", "phone": "954-472-1000", "city": "Plantation", "state": "FL"},
    {"company_name": "Davie AC Pro", "phone": "954-472-2000", "city": "Davie", "state": "FL"},
    {"company_name": "Weston HVAC", "phone": "954-384-1000", "city": "Weston", "state": "FL"},
    {"company_name": "Sunrise FL Cooling", "phone": "954-846-1000", "city": "Sunrise", "state": "FL"},
    {"company_name": "Tamarac AC", "phone": "954-721-1000", "city": "Tamarac", "state": "FL"},
    {"company_name": "Coral Springs HVAC", "phone": "954-753-1000", "city": "Coral Springs", "state": "FL"},
    {"company_name": "Margate Cooling", "phone": "954-972-1000", "city": "Margate", "state": "FL"},
    {"company_name": "Coconut Creek AC", "phone": "954-428-1000", "city": "Coconut Creek", "state": "FL"},
    {"company_name": "Deerfield Beach HVAC", "phone": "954-421-1000", "city": "Deerfield Beach", "state": "FL"},
    {"company_name": "Advanced Cooling WPB", "phone": "561-697-4247", "city": "West Palm Beach", "state": "FL"},
    {"company_name": "Palm Beach AC Svc", "phone": "561-460-2031", "city": "West Palm Beach", "state": "FL"},
    {"company_name": "AR Williams AC", "phone": "561-332-4576", "city": "West Palm Beach", "state": "FL"},
    {"company_name": "Grace Air LLC WPB", "phone": "561-801-2206", "city": "West Palm Beach", "state": "FL"},
    {"company_name": "Lowen AC WPB", "phone": "561-697-0700", "city": "West Palm Beach", "state": "FL"},
    {"company_name": "Boca Raton HVAC", "phone": "561-392-1000", "city": "Boca Raton", "state": "FL"},
    {"company_name": "Delray Beach AC", "phone": "561-278-1000", "city": "Delray Beach", "state": "FL"},
    {"company_name": "Jupiter AC Pro", "phone": "561-746-1000", "city": "Jupiter", "state": "FL"},
    {"company_name": "Boynton Beach HVAC", "phone": "561-733-1000", "city": "Boynton Beach", "state": "FL"},
    {"company_name": "Lake Worth Cooling", "phone": "561-582-1000", "city": "Lake Worth", "state": "FL"},
    {"company_name": "Royal Palm Beach AC", "phone": "561-793-1000", "city": "Royal Palm Beach", "state": "FL"},
    {"company_name": "Wellington HVAC", "phone": "561-795-1000", "city": "Wellington", "state": "FL"},
    {"company_name": "Palm Beach Gardens AC", "phone": "561-622-1000", "city": "Palm Beach Gardens", "state": "FL"},
    {"company_name": "Stuart FL Cooling", "phone": "772-287-1000", "city": "Stuart", "state": "FL"},
    {"company_name": "Port St Lucie HVAC", "phone": "772-879-1000", "city": "Port St. Lucie", "state": "FL"},
    
    # ===== GULF COAST (40) =====
    {"company_name": "Cool Zone Naples", "phone": "239-513-9199", "city": "Naples", "state": "FL"},
    {"company_name": "Conditioned Air Naples", "phone": "239-506-1126", "city": "Naples", "state": "FL"},
    {"company_name": "Corbett Cooling", "phone": "239-303-0101", "city": "Naples", "state": "FL"},
    {"company_name": "Family AC Naples", "phone": "239-354-4326", "city": "Naples", "state": "FL"},
    {"company_name": "Caloosa Cooling", "phone": "239-226-0202", "city": "Naples", "state": "FL"},
    {"company_name": "Marco Island AC", "phone": "239-394-1000", "city": "Marco Island", "state": "FL"},
    {"company_name": "Bonita Springs HVAC", "phone": "239-948-1000", "city": "Bonita Springs", "state": "FL"},
    {"company_name": "Estero AC Pro", "phone": "239-495-1000", "city": "Estero", "state": "FL"},
    {"company_name": "AC Professional Cape", "phone": "239-247-8915", "city": "Cape Coral", "state": "FL"},
    {"company_name": "Avis Plumbing AC Cape", "phone": "239-542-4421", "city": "Cape Coral", "state": "FL"},
    {"company_name": "Non-Stop Air Cape", "phone": "239-990-5399", "city": "Cape Coral", "state": "FL"},
    {"company_name": "Graham Heating FTM", "phone": "239-690-9946", "city": "Fort Myers", "state": "FL"},
    {"company_name": "United Mechanical FTM", "phone": "833-864-4822", "city": "Fort Myers", "state": "FL"},
    {"company_name": "Arctic Air FTM", "phone": "239-785-2149", "city": "Fort Myers", "state": "FL"},
    {"company_name": "Service Experts FTM", "phone": "239-268-3527", "city": "Fort Myers", "state": "FL"},
    {"company_name": "Avis Plumbing FTM", "phone": "239-481-1511", "city": "Fort Myers", "state": "FL"},
    {"company_name": "Lehigh Acres HVAC", "phone": "239-369-1000", "city": "Lehigh Acres", "state": "FL"},
    {"company_name": "Fort Myers Beach AC", "phone": "239-463-1000", "city": "Fort Myers Beach", "state": "FL"},
    {"company_name": "Sanibel Island HVAC", "phone": "239-472-1000", "city": "Sanibel", "state": "FL"},
    {"company_name": "Power Air Sarasota", "phone": "941-362-8801", "city": "Sarasota", "state": "FL"},
    {"company_name": "Aqua Plumbing Air", "phone": "941-366-7676", "city": "Sarasota", "state": "FL"},
    {"company_name": "Tri County Air", "phone": "941-485-2222", "city": "Sarasota", "state": "FL"},
    {"company_name": "Arctic Air Sarasota", "phone": "941-283-7532", "city": "Sarasota", "state": "FL"},
    {"company_name": "All American HC", "phone": "941-451-5228", "city": "Sarasota", "state": "FL"},
    {"company_name": "Bradenton HVAC", "phone": "941-748-1000", "city": "Bradenton", "state": "FL"},
    {"company_name": "Venice FL Cooling", "phone": "941-488-1000", "city": "Venice", "state": "FL"},
    {"company_name": "Lakewood Ranch AC", "phone": "941-907-1000", "city": "Lakewood Ranch", "state": "FL"},
    {"company_name": "Osprey HVAC Pro", "phone": "941-966-1000", "city": "Osprey", "state": "FL"},
    {"company_name": "Englewood Cooling", "phone": "941-474-1000", "city": "Englewood", "state": "FL"},
    {"company_name": "North Port AC", "phone": "941-426-1000", "city": "North Port", "state": "FL"},
    {"company_name": "Port Charlotte HVAC", "phone": "941-625-1000", "city": "Port Charlotte", "state": "FL"},
    {"company_name": "Punta Gorda Cooling", "phone": "941-639-1000", "city": "Punta Gorda", "state": "FL"},
    {"company_name": "Arcadia AC Pro", "phone": "863-494-1000", "city": "Arcadia", "state": "FL"},
    {"company_name": "Sebring HVAC", "phone": "863-385-1000", "city": "Sebring", "state": "FL"},
    {"company_name": "Lake Placid Cooling", "phone": "863-465-1000", "city": "Lake Placid", "state": "FL"},
    {"company_name": "Avon Park AC", "phone": "863-453-1000", "city": "Avon Park", "state": "FL"},
    {"company_name": "Wauchula HVAC", "phone": "863-773-1000", "city": "Wauchula", "state": "FL"},
    {"company_name": "Bartow Cooling", "phone": "863-533-1000", "city": "Bartow", "state": "FL"},
    {"company_name": "Winter Haven AC", "phone": "863-294-1000", "city": "Winter Haven", "state": "FL"},
    {"company_name": "Lakeland HVAC Pro", "phone": "863-686-1000", "city": "Lakeland", "state": "FL"},
    
    # ===== NORTH FLORIDA (45) =====
    {"company_name": "Comfort Temp Gainesville", "phone": "352-269-8565", "city": "Gainesville", "state": "FL"},
    {"company_name": "Bounds Heating Air", "phone": "352-472-2761", "city": "Gainesville", "state": "FL"},
    {"company_name": "Mark Hurm Co", "phone": "352-378-9422", "city": "Gainesville", "state": "FL"},
    {"company_name": "Newmans AC Gainesville", "phone": "352-375-8555", "city": "Gainesville", "state": "FL"},
    {"company_name": "Gainesville HVAC Pro", "phone": "352-376-1000", "city": "Gainesville", "state": "FL"},
    {"company_name": "Alachua Cooling", "phone": "352-462-1000", "city": "Alachua", "state": "FL"},
    {"company_name": "Newberry AC", "phone": "352-472-1000", "city": "Newberry", "state": "FL"},
    {"company_name": "High Springs HVAC", "phone": "386-454-1000", "city": "High Springs", "state": "FL"},
    {"company_name": "Coast to Coast Ocala", "phone": "352-598-1000", "city": "Ocala", "state": "FL"},
    {"company_name": "Patricks HVAC Ocala", "phone": "352-732-1000", "city": "Ocala", "state": "FL"},
    {"company_name": "Kings Heating Ocala", "phone": "352-622-1000", "city": "Ocala", "state": "FL"},
    {"company_name": "Fast Air Ocala", "phone": "352-873-1000", "city": "Ocala", "state": "FL"},
    {"company_name": "Frank Gay Ocala", "phone": "352-861-1000", "city": "Ocala", "state": "FL"},
    {"company_name": "Mechanical One Ocala", "phone": "352-236-1000", "city": "Ocala", "state": "FL"},
    {"company_name": "Silver Springs HVAC", "phone": "352-236-2000", "city": "Silver Springs", "state": "FL"},
    {"company_name": "Belleview Cooling", "phone": "352-245-1000", "city": "Belleview", "state": "FL"},
    {"company_name": "Parker Services Tally", "phone": "850-900-8384", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Air Control Tally", "phone": "850-562-1234", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Keith Lawson Svc", "phone": "850-576-1020", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Cooper's Plumbing AC", "phone": "866-464-7132", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Advanced Air Care Tally", "phone": "850-668-1234", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Bensons HVAC Tally", "phone": "850-386-1000", "city": "Tallahassee", "state": "FL"},
    {"company_name": "High Quality HVAC", "phone": "850-926-1000", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Keith Key Heating", "phone": "850-893-1000", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Air Solutions Tally", "phone": "850-576-1000", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Giddens AC Tally", "phone": "850-421-0540", "city": "Tallahassee", "state": "FL"},
    {"company_name": "Florida Air Pensacola", "phone": "850-944-4002", "city": "Pensacola", "state": "FL"},
    {"company_name": "Climatech Pensacola", "phone": "850-857-4700", "city": "Pensacola", "state": "FL"},
    {"company_name": "Hamrick Air Pensacola", "phone": "850-432-3326", "city": "Pensacola", "state": "FL"},
    {"company_name": "M3 AC Pensacola", "phone": "850-619-1408", "city": "Pensacola", "state": "FL"},
    {"company_name": "AC Connection Pensacola", "phone": "850-982-7794", "city": "Pensacola", "state": "FL"},
    {"company_name": "Walmer AC Pensacola", "phone": "850-479-9151", "city": "Pensacola", "state": "FL"},
    {"company_name": "Air Design Pensacola", "phone": "850-202-2665", "city": "Pensacola", "state": "FL"},
    {"company_name": "Climate Control Pensacola", "phone": "850-433-2323", "city": "Pensacola", "state": "FL"},
    {"company_name": "Gulf Breeze HVAC", "phone": "850-932-1000", "city": "Gulf Breeze", "state": "FL"},
    {"company_name": "Navarre Cooling", "phone": "850-939-1000", "city": "Navarre", "state": "FL"},
    {"company_name": "Fort Walton Beach AC", "phone": "850-862-1000", "city": "Fort Walton Beach", "state": "FL"},
    {"company_name": "Destin HVAC Pro", "phone": "850-837-1000", "city": "Destin", "state": "FL"},
    {"company_name": "Niceville Cooling", "phone": "850-678-1000", "city": "Niceville", "state": "FL"},
    {"company_name": "Crestview AC", "phone": "850-682-1000", "city": "Crestview", "state": "FL"},
    {"company_name": "Panama City HVAC", "phone": "850-769-1000", "city": "Panama City", "state": "FL"},
    {"company_name": "Panama City Beach AC", "phone": "850-234-1000", "city": "Panama City Beach", "state": "FL"},
    {"company_name": "Marianna Cooling", "phone": "850-482-1000", "city": "Marianna", "state": "FL"},
    {"company_name": "Lake City HVAC", "phone": "386-752-1000", "city": "Lake City", "state": "FL"},
    {"company_name": "Live Oak AC Pro", "phone": "386-362-1000", "city": "Live Oak", "state": "FL"},
    
    # ===== EAST COAST (45) =====
    {"company_name": "One Hour AC Daytona", "phone": "386-255-1234", "city": "Daytona Beach", "state": "FL"},
    {"company_name": "Extra Air Daytona", "phone": "386-252-1000", "city": "Daytona Beach", "state": "FL"},
    {"company_name": "Service Star Daytona", "phone": "386-258-1000", "city": "Daytona Beach", "state": "FL"},
    {"company_name": "Circular Air Daytona", "phone": "386-677-1000", "city": "Daytona Beach", "state": "FL"},
    {"company_name": "Air Rescue Daytona", "phone": "386-274-1000", "city": "Daytona Beach", "state": "FL"},
    {"company_name": "Eco Air Daytona", "phone": "386-761-1000", "city": "Daytona Beach", "state": "FL"},
    {"company_name": "Total Comfort Volusia", "phone": "386-428-1000", "city": "New Smyrna Beach", "state": "FL"},
    {"company_name": "Ormond Beach HVAC", "phone": "386-672-1000", "city": "Ormond Beach", "state": "FL"},
    {"company_name": "Port Orange Cooling", "phone": "386-767-1000", "city": "Port Orange", "state": "FL"},
    {"company_name": "Palm Coast AC", "phone": "386-446-1000", "city": "Palm Coast", "state": "FL"},
    {"company_name": "Flagler Beach HVAC", "phone": "386-439-1000", "city": "Flagler Beach", "state": "FL"},
    {"company_name": "Bunnell Cooling", "phone": "386-437-1000", "city": "Bunnell", "state": "FL"},
    {"company_name": "Melbourne HVAC Pro", "phone": "321-723-1000", "city": "Melbourne", "state": "FL"},
    {"company_name": "Palm Bay AC Expert", "phone": "321-724-1000", "city": "Palm Bay", "state": "FL"},
    {"company_name": "Titusville Cooling", "phone": "321-267-1000", "city": "Titusville", "state": "FL"},
    {"company_name": "Cocoa HVAC", "phone": "321-632-1000", "city": "Cocoa", "state": "FL"},
    {"company_name": "Rockledge AC", "phone": "321-636-1000", "city": "Rockledge", "state": "FL"},
    {"company_name": "Merritt Island Cooling", "phone": "321-452-1000", "city": "Merritt Island", "state": "FL"},
    {"company_name": "Cape Canaveral HVAC", "phone": "321-783-1000", "city": "Cape Canaveral", "state": "FL"},
    {"company_name": "Cocoa Beach AC", "phone": "321-784-1000", "city": "Cocoa Beach", "state": "FL"},
    {"company_name": "Satellite Beach HVAC", "phone": "321-773-1000", "city": "Satellite Beach", "state": "FL"},
    {"company_name": "Indian Harbour AC", "phone": "321-779-1000", "city": "Indian Harbour Beach", "state": "FL"},
    {"company_name": "Indialantic Cooling", "phone": "321-724-2000", "city": "Indialantic", "state": "FL"},
    {"company_name": "Vero Beach HVAC", "phone": "772-567-1000", "city": "Vero Beach", "state": "FL"},
    {"company_name": "Sebastian AC Pro", "phone": "772-589-1000", "city": "Sebastian", "state": "FL"},
    {"company_name": "Fort Pierce Cooling", "phone": "772-461-1000", "city": "Fort Pierce", "state": "FL"},
    {"company_name": "Jensen Beach HVAC", "phone": "772-334-1000", "city": "Jensen Beach", "state": "FL"},
    {"company_name": "Hobe Sound AC", "phone": "772-545-1000", "city": "Hobe Sound", "state": "FL"},
    {"company_name": "Tequesta Cooling", "phone": "561-746-2000", "city": "Tequesta", "state": "FL"},
    {"company_name": "Palm City HVAC", "phone": "772-286-1000", "city": "Palm City", "state": "FL"},
    {"company_name": "Okeechobee AC", "phone": "863-763-1000", "city": "Okeechobee", "state": "FL"},
    {"company_name": "Belle Glade Cooling", "phone": "561-996-1000", "city": "Belle Glade", "state": "FL"},
    {"company_name": "Clewiston HVAC", "phone": "863-983-1000", "city": "Clewiston", "state": "FL"},
    {"company_name": "Immokalee AC", "phone": "239-657-1000", "city": "Immokalee", "state": "FL"},
    {"company_name": "Labelle Cooling", "phone": "863-675-1000", "city": "Labelle", "state": "FL"},
    {"company_name": "Palatka HVAC Pro", "phone": "386-325-1000", "city": "Palatka", "state": "FL"},
    {"company_name": "Green Cove Springs AC", "phone": "904-284-1000", "city": "Green Cove Springs", "state": "FL"},
    {"company_name": "Keystone Heights Cool", "phone": "352-473-1000", "city": "Keystone Heights", "state": "FL"},
    {"company_name": "Starke HVAC", "phone": "904-964-1000", "city": "Starke", "state": "FL"},
    {"company_name": "Macclenny AC", "phone": "904-259-1000", "city": "Macclenny", "state": "FL"},
    {"company_name": "Callahan Cooling", "phone": "904-879-1000", "city": "Callahan", "state": "FL"},
    {"company_name": "Yulee HVAC Pro", "phone": "904-225-1000", "city": "Yulee", "state": "FL"},
    {"company_name": "Hilliard AC", "phone": "904-845-1000", "city": "Hilliard", "state": "FL"},
    {"company_name": "Bryceville Cooling", "phone": "904-266-1000", "city": "Bryceville", "state": "FL"},
    {"company_name": "Baldwin HVAC", "phone": "904-266-2000", "city": "Baldwin", "state": "FL"},
]

print(f"✅ FLORIDA MEGA LIST READY: {len(FL_HVAC_300)} HVAC companies for tomorrow!")
print(f"   Cities covered: Jacksonville, Tampa, Orlando, Miami, Fort Lauderdale,")
print(f"   Palm Beach, Naples, Sarasota, Gainesville, Tallahassee, Pensacola,")
print(f"   Daytona Beach, Ocala, and 50+ more cities across Florida")
