import os
from supabase import create_client

def init_tables():
    url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    
    if not url or not key:
        print("Skipping DB Init (No Keys)")
        return

    sb = create_client(url, key)
    
    print("📡 Initializing Supabase Tables via Helper...")
    
    # We can't easily run raw SQL via the py client unless using RPC or direct pg driver,
    # but let's try to verify if tables exist by inserting a test record.
    # If using `supabase` library we usually need the tables to exist.
    # For a real migration we'd use 'psycopg2' or an SQL editor.
    # HOWEVER, for this "Serverless" pivot, if tables don't exist, we might fail.
    # Let's try to create them via a generic RPC call if enabled, or simple instructions.
    
    # Since we can't guarantee RPC for raw SQL, we will instruct the user or assume they exist.
    # BUT wait, the instructions said "Migrate to Supabase".
    # I will create a script that tries to insert a dummy lead. If it fails, we know tables are missing.
    
    try:
         sb.table("leads").insert({"email": "init_check@test.com", "name": "Init Check", "source": "SETUP"}).execute()
         print("✅ 'leads' table exists and is writable.")
    except Exception as e:
         print(f"⚠️ 'leads' table might be missing or limited: {e}")
         print("ACTION: You must go to Supabase Dashboard -> SQL Editor and run:")
         print("""
         CREATE TABLE IF NOT EXISTS leads (
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
             email TEXT,
             phone TEXT,
             name TEXT,
             source TEXT,
             metadata TEXT
         );
         
         CREATE TABLE IF NOT EXISTS interactions (
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
             type TEXT,
             summary TEXT,
             transcript TEXT
         );
         """)

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    init_tables()
