import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

def migrate():
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        print("❌ No DATABASE_URL found.")
        return

    print("🚀 Connecting to Supabase via Postgres...")
    try:
        conn = psycopg2.connect(db_url)
        cur = conn.cursor()
        
        # LEADS TABLE
        print("🛠️  Migrating 'leads'...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS leads (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
                email TEXT,
                phone TEXT,
                name TEXT,
                source TEXT,
                metadata TEXT
            );
        """)
        
        # INTERACTIONS TABLE
        print("🛠️  Migrating 'interactions'...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS interactions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
                type TEXT,
                summary TEXT,
                transcript TEXT
            );
        """)
        
        conn.commit()
        cur.close()
        conn.close()
        print("✅ Migration Complete. Tables Ready.")
        
    except Exception as e:
        print(f"❌ Migration Failed: {e}")

if __name__ == "__main__":
    migrate()
