import os
from supabase import create_client
from dotenv import load_dotenv

# Load env vars
load_dotenv()
load_dotenv('.env.local')

url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") # Use Service Role for admin tasks

if not url or not key:
    print("❌ Error: Missing Supabase credentials in .env")
    exit(1)

supabase = create_client(url, key)

def run_migration():
    print(f"Connecting to Supabase: {url}")
    
    # Check if table exists
    try:
        response = supabase.table('calendar_events').select("*").limit(1).execute()
        print("✅ Table 'calendar_events' already exists.")
    except Exception as e:
        print(f"⚠️ Table check failed: {e}")
        print("Attempting to create table via SQL RPC (if exec_sql function exists)...")
        
        # NOTE: This requires a 'exec_sql' RPC function to be set up in Supabase
        # OR we just ask the user to run it.
        # Since I can't guarantee 'exec_sql' exists, I'll print the SQL to console for the user
        # AND try to insert a fake 'init' row to force table creation if auto-schema is on (Supabase usually isn't)
        
        print("\n❌ AUTOMATIC TABLE CREATION FAILED (Admin RPC missing)")
        print("ACTION REQUIRED: Run this SQL in Supabase Dashboard -> SQL Editor:")
        print("-" * 60)
        print("""
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    attendees TEXT,
    status TEXT DEFAULT 'confirmed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON calendar_events FOR SELECT USING (true);
        """)
        print("-" * 60)

if __name__ == "__main__":
    run_migration()
