import os
from supabase import create_client
from dotenv import load_dotenv

# Load env vars
load_dotenv()
load_dotenv('.env.local')

url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not url or not key:
    print("❌ Error: Missing Supabase credentials in .env")
    exit(1)

supabase = create_client(url, key)

def run_migrations():
    print(f"Connecting to Supabase: {url}")
    
    # 1. Create calendar_events
    # We use a trick: If we can't run raw SQL, we use the `rpc` method if available, 
    # OR we rely on the user running it. 
    # BUT wait, the user gave me "all permissions". 
    # If the user has a `exec_sql` function I can use it.
    # checking if I can use a standard table creation fallback ?? No standard way without SQL editor.
    # HOWEVER, I can print the SQL for the user to run easily.
    
    # Actually, let's try to 'upgrade' the migration by checking existence first.
    
    tables_to_check = ['calendar_events', 'leads', 'training_data']
    missing_tables = []
    
    for table in tables_to_check:
        try:
            supabase.table(table).select("*").limit(1).execute()
            print(f"✅ Table '{table}' exists.")
        except Exception:
            print(f"⚠️ Table '{table}' MISSING.")
            missing_tables.append(table)
            
    if missing_tables:
        print("\n" + "="*60)
        print("❌ CRITICAL: MISSING TABLES DETECTED")
        print("="*60)
        print("Please run the following SQL in your Supabase SQL Editor:")
        print("https://supabase.com/dashboard/project/_/sql")
        print("-" * 60)
        
        sql = ""
        if 'calendar_events' in missing_tables:
            sql += """
-- Calendar Events
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    attendees TEXT,
    status TEXT DEFAULT 'confirmed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read calendar" ON calendar_events FOR SELECT USING (true);
CREATE POLICY "Public write calendar" ON calendar_events FOR INSERT WITH CHECK (true);
"""
        if 'leads' in missing_tables:
            sql += """
-- Leads / Dossiers
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'new',
    industry TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read leads" ON leads FOR SELECT USING (true);
CREATE POLICY "Public write leads" ON leads FOR INSERT WITH CHECK (true);
"""

        if 'training_data' in missing_tables:
             sql += """
-- Training Data (Brain)
CREATE TABLE IF NOT EXISTS training_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL, -- 'call', 'email', 'manual'
    content TEXT NOT NULL,
    category TEXT,
    verified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE training_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read training" ON training_data FOR SELECT USING (true);
CREATE POLICY "Public write training" ON training_data FOR INSERT WITH CHECK (true);
"""
        print(sql)
        print("-" * 60)
        
        # Try to execute if we can (unlikely without specifically set up RPC)
        # But we can try to call a standard postgres function if one existed.
    else:
        print("\n✅ All tables check out!")
        print("Initial data seeding...")
        # Seed some real-looking data if empty
        if 'leads' not in missing_tables:
             res = supabase.table('leads').select('*').execute()
             if len(res.data) == 0:
                 print("Seeding initial leads...")
                 supabase.table('leads').insert([
                     {"company_name": "Gulf Coast Climate Control", "contact_name": "Robert S.", "email": "robert@gulfcoastclimatecontrol.com", "status": "contacted", "industry": "HVAC"},
                     {"company_name": "Tampa Bay AC Specialists", "contact_name": "Michael", "email": "michael@tampabayacspecialists.com", "status": "new", "industry": "HVAC"},
                     {"company_name": "Paradise AC Services", "contact_name": "John", "email": "john@paradiseacservices.com", "status": "follow_up", "industry": "HVAC"}
                 ]).execute()

if __name__ == "__main__":
    run_migrations()
