-- Run this in your Supabase SQL Editor
-- 1. Office Inventory Table
create table if not exists office_inventory (
    id bigint generated by default as identity primary key,
    item text not null unique,
    quantity integer default 0,
    updated_at timestamp with time zone default timezone('utc'::text, now())
);
-- 2. Office Tasks Table
create table if not exists office_tasks (
    id bigint generated by default as identity primary key,
    description text not null,
    status text default 'pending',
    -- pending, completed
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 3. Initial Inventory Data (Optional)
insert into office_inventory (item, quantity)
values ('paper', 100),
    ('coffee', 2),
    ('ink', 5) on conflict (item) do nothing;