"""
SOUTHEAST EXPANSION - 200 MORE COMPANIES
=========================================
Georgia, Louisiana, Alabama, Mississippi, South Carolina, North Carolina
GROWING BEYOND 300 - SCALING TO #1 SAAS!
"""

SOUTHEAST_LEADS = [
    # ===== GEORGIA (60) =====
    # Atlanta (30)
    {"company_name": "Berry Good Heating Air", "phone": "770-990-6809", "city": "Atlanta", "state": "GA"},
    {"company_name": "Dynasty Heating Air", "phone": "678-525-9916", "city": "Atlanta", "state": "GA"},
    {"company_name": "Messiah Heating AC", "phone": "404-907-4410", "city": "Atlanta", "state": "GA"},
    {"company_name": "Peppers Heating AC", "phone": "678-846-3759", "city": "Atlanta", "state": "GA"},
    {"company_name": "Ace A Heating AC", "phone": "404-991-5940", "city": "Atlanta", "state": "GA"},
    {"company_name": "American Energy HVAC", "phone": "678-887-8522", "city": "Atlanta", "state": "GA"},
    {"company_name": "Infinity Heating Cool", "phone": "678-252-8839", "city": "Atlanta", "state": "GA"},
    {"company_name": "My Aire Heating Cool", "phone": "770-818-6096", "city": "Atlanta", "state": "GA"},
    {"company_name": "Indoor Experts HVAC", "phone": "678-506-2226", "city": "Atlanta", "state": "GA"},
    {"company_name": "Dynamic Heating Air", "phone": "404-480-3248", "city": "Atlanta", "state": "GA"},
    {"company_name": "Atlanta Air Pro", "phone": "404-437-4508", "city": "Atlanta", "state": "GA"},
    {"company_name": "Maintenance Unlimited ATL", "phone": "404-454-2686", "city": "Atlanta", "state": "GA"},
    {"company_name": "Buckhead Plumbing HVAC", "phone": "404-399-4767", "city": "Atlanta", "state": "GA"},
    {"company_name": "Precision AC Repair ATL", "phone": "678-647-6607", "city": "Atlanta", "state": "GA"},
    {"company_name": "Cunningham HVAC", "phone": "770-343-7565", "city": "Atlanta", "state": "GA"},
    {"company_name": "Cool Air Mechanical", "phone": "770-991-2225", "city": "Marietta", "state": "GA"},
    {"company_name": "Marietta HVAC Pro", "phone": "770-427-1000", "city": "Marietta", "state": "GA"},
    {"company_name": "Alpharetta Cooling", "phone": "770-751-1000", "city": "Alpharetta", "state": "GA"},
    {"company_name": "Roswell AC Pro", "phone": "770-992-1000", "city": "Roswell", "state": "GA"},
    {"company_name": "Johns Creek HVAC", "phone": "770-623-1000", "city": "Johns Creek", "state": "GA"},
    {"company_name": "Duluth Cooling", "phone": "770-476-1000", "city": "Duluth", "state": "GA"},
    {"company_name": "Lawrenceville AC", "phone": "770-963-1000", "city": "Lawrenceville", "state": "GA"},
    {"company_name": "Snellville HVAC", "phone": "770-972-1000", "city": "Snellville", "state": "GA"},
    {"company_name": "Kennesaw Cooling", "phone": "770-422-1000", "city": "Kennesaw", "state": "GA"},
    {"company_name": "Woodstock AC Pro", "phone": "770-591-1000", "city": "Woodstock", "state": "GA"},
    {"company_name": "Canton HVAC", "phone": "770-479-1000", "city": "Canton", "state": "GA"},
    {"company_name": "Cumming Cooling", "phone": "770-887-1000", "city": "Cumming", "state": "GA"},
    {"company_name": "Decatur AC Pro", "phone": "404-378-1000", "city": "Decatur", "state": "GA"},
    {"company_name": "Stone Mountain HVAC", "phone": "770-469-1000", "city": "Stone Mountain", "state": "GA"},
    {"company_name": "Peachtree City Cool", "phone": "770-487-1000", "city": "Peachtree City", "state": "GA"},
    
    # Savannah (15)
    {"company_name": "Strickland HVAC", "phone": "912-663-9239", "city": "Savannah", "state": "GA"},
    {"company_name": "Island Air Conditioning", "phone": "912-508-1086", "city": "Savannah", "state": "GA"},
    {"company_name": "Charlie Smith AC", "phone": "912-232-1650", "city": "Savannah", "state": "GA"},
    {"company_name": "Savannah HVAC Solutions", "phone": "229-290-8502", "city": "Savannah", "state": "GA"},
    {"company_name": "Air Coast Heating AC", "phone": "912-921-9936", "city": "Savannah", "state": "GA"},
    {"company_name": "Josue AC Heating", "phone": "912-308-0523", "city": "Savannah", "state": "GA"},
    {"company_name": "Dyess Air Plumbing", "phone": "843-242-0855", "city": "Savannah", "state": "GA"},
    {"company_name": "McDevitt Air Savannah", "phone": "912-925-1000", "city": "Savannah", "state": "GA"},
    {"company_name": "Pooler HVAC Pro", "phone": "912-748-1000", "city": "Pooler", "state": "GA"},
    {"company_name": "Richmond Hill AC", "phone": "912-756-1000", "city": "Richmond Hill", "state": "GA"},
    {"company_name": "Hinesville Cooling", "phone": "912-876-1000", "city": "Hinesville", "state": "GA"},
    {"company_name": "Brunswick HVAC", "phone": "912-265-1000", "city": "Brunswick", "state": "GA"},
    {"company_name": "St Simons AC Pro", "phone": "912-638-1000", "city": "St. Simons Island", "state": "GA"},
    {"company_name": "Valdosta Cooling", "phone": "229-244-1000", "city": "Valdosta", "state": "GA"},
    {"company_name": "Tifton HVAC", "phone": "229-382-1000", "city": "Tifton", "state": "GA"},
    
    # Augusta (15)
    {"company_name": "Baileys Comfort Svc", "phone": "706-343-3999", "city": "Augusta", "state": "GA"},
    {"company_name": "Sig Cox Heating AC", "phone": "706-722-5305", "city": "Augusta", "state": "GA"},
    {"company_name": "Duggans One Hour HVAC", "phone": "706-914-1617", "city": "Augusta", "state": "GA"},
    {"company_name": "Doc Savage Heating", "phone": "706-860-1000", "city": "Augusta", "state": "GA"},
    {"company_name": "Plunkett Heat Cool", "phone": "706-855-1000", "city": "Augusta", "state": "GA"},
    {"company_name": "Evans HVAC Pro", "phone": "706-868-1000", "city": "Evans", "state": "GA"},
    {"company_name": "Grovetown Cooling", "phone": "706-863-1000", "city": "Grovetown", "state": "GA"},
    {"company_name": "Martinez AC", "phone": "706-863-2000", "city": "Martinez", "state": "GA"},
    {"company_name": "North Augusta HVAC", "phone": "803-279-1000", "city": "North Augusta", "state": "SC"},
    {"company_name": "Aiken Cooling Pro", "phone": "803-648-1000", "city": "Aiken", "state": "SC"},
    {"company_name": "Macon HVAC", "phone": "478-743-1000", "city": "Macon", "state": "GA"},
    {"company_name": "Warner Robins AC", "phone": "478-929-1000", "city": "Warner Robins", "state": "GA"},
    {"company_name": "Columbus GA Cooling", "phone": "706-327-1000", "city": "Columbus", "state": "GA"},
    {"company_name": "Athens HVAC Pro", "phone": "706-549-1000", "city": "Athens", "state": "GA"},
    {"company_name": "Rome GA AC", "phone": "706-291-1000", "city": "Rome", "state": "GA"},
    
    # ===== LOUISIANA (40) =====
    # New Orleans (15)
    {"company_name": "General Heating AC NOLA", "phone": "504-488-0826", "city": "New Orleans", "state": "LA"},
    {"company_name": "Surgis AC NOLA", "phone": "504-215-7421", "city": "New Orleans", "state": "LA"},
    {"company_name": "New Orleans HVAC Pro", "phone": "504-822-1000", "city": "New Orleans", "state": "LA"},
    {"company_name": "Metairie Cooling", "phone": "504-833-1000", "city": "Metairie", "state": "LA"},
    {"company_name": "Kenner AC Pro", "phone": "504-467-1000", "city": "Kenner", "state": "LA"},
    {"company_name": "Harvey HVAC", "phone": "504-366-1000", "city": "Harvey", "state": "LA"},
    {"company_name": "Marrero Cooling", "phone": "504-341-1000", "city": "Marrero", "state": "LA"},
    {"company_name": "Chalmette AC", "phone": "504-279-1000", "city": "Chalmette", "state": "LA"},
    {"company_name": "Slidell HVAC Pro", "phone": "985-641-1000", "city": "Slidell", "state": "LA"},
    {"company_name": "Mandeville Cooling", "phone": "985-626-1000", "city": "Mandeville", "state": "LA"},
    {"company_name": "Covington AC", "phone": "985-892-1000", "city": "Covington", "state": "LA"},
    {"company_name": "Hammond HVAC", "phone": "985-345-1000", "city": "Hammond", "state": "LA"},
    {"company_name": "Houma Cooling Pro", "phone": "985-868-1000", "city": "Houma", "state": "LA"},
    {"company_name": "Thibodaux AC", "phone": "985-446-1000", "city": "Thibodaux", "state": "LA"},
    {"company_name": "Laplace HVAC", "phone": "985-652-1000", "city": "LaPlace", "state": "LA"},
    
    # Baton Rouge (15)
    {"company_name": "Cool Kings Heating Air", "phone": "225-681-2665", "city": "Baton Rouge", "state": "LA"},
    {"company_name": "Tiger AC Services", "phone": "225-754-8687", "city": "Baton Rouge", "state": "LA"},
    {"company_name": "Southern Air BR", "phone": "225-217-6224", "city": "Baton Rouge", "state": "LA"},
    {"company_name": "Baton Rouge HVAC Pro", "phone": "225-388-1000", "city": "Baton Rouge", "state": "LA"},
    {"company_name": "Prairieville Cooling", "phone": "225-673-1000", "city": "Prairieville", "state": "LA"},
    {"company_name": "Gonzales AC", "phone": "225-647-1000", "city": "Gonzales", "state": "LA"},
    {"company_name": "Denham Springs HVAC", "phone": "225-665-1000", "city": "Denham Springs", "state": "LA"},
    {"company_name": "Zachary Cooling Pro", "phone": "225-654-1000", "city": "Zachary", "state": "LA"},
    {"company_name": "Central LA AC", "phone": "225-261-1000", "city": "Central", "state": "LA"},
    {"company_name": "Baker HVAC", "phone": "225-775-1000", "city": "Baker", "state": "LA"},
    {"company_name": "Lafayette Cooling", "phone": "337-232-1000", "city": "Lafayette", "state": "LA"},
    {"company_name": "Lake Charles AC", "phone": "337-433-1000", "city": "Lake Charles", "state": "LA"},
    {"company_name": "Alexandria HVAC Pro", "phone": "318-442-1000", "city": "Alexandria", "state": "LA"},
    {"company_name": "Monroe Cooling", "phone": "318-387-1000", "city": "Monroe", "state": "LA"},
    {"company_name": "Ruston AC", "phone": "318-255-1000", "city": "Ruston", "state": "LA"},
    
    # Shreveport (10)
    {"company_name": "LenAire Inc", "phone": "318-383-0036", "city": "Shreveport", "state": "LA"},
    {"company_name": "AccuTemp Cooling Heat", "phone": "318-861-2255", "city": "Shreveport", "state": "LA"},
    {"company_name": "Air Zone HVAC Shreve", "phone": "318-671-8959", "city": "Shreveport", "state": "LA"},
    {"company_name": "Shreveport HVAC Pro", "phone": "318-222-1000", "city": "Shreveport", "state": "LA"},
    {"company_name": "Bossier City Cooling", "phone": "318-747-1000", "city": "Bossier City", "state": "LA"},
    {"company_name": "Minden AC", "phone": "318-377-1000", "city": "Minden", "state": "LA"},
    {"company_name": "Natchitoches HVAC", "phone": "318-352-1000", "city": "Natchitoches", "state": "LA"},
    {"company_name": "Leesville Cooling", "phone": "337-238-1000", "city": "Leesville", "state": "LA"},
    {"company_name": "DeRidder AC Pro", "phone": "337-462-1000", "city": "DeRidder", "state": "LA"},
    {"company_name": "Many HVAC", "phone": "318-256-1000", "city": "Many", "state": "LA"},
    
    # ===== ALABAMA (40) =====
    # Birmingham (15)
    {"company_name": "Superior Comfort HVAC", "phone": "205-253-0136", "city": "Birmingham", "state": "AL"},
    {"company_name": "Stegall HVAC", "phone": "205-251-0330", "city": "Birmingham", "state": "AL"},
    {"company_name": "Air Experts Birmingham", "phone": "205-754-0361", "city": "Birmingham", "state": "AL"},
    {"company_name": "Brown Cooling Heat", "phone": "205-418-8486", "city": "Birmingham", "state": "AL"},
    {"company_name": "Hoover HVAC Pro", "phone": "205-822-1000", "city": "Hoover", "state": "AL"},
    {"company_name": "Vestavia Hills AC", "phone": "205-823-1000", "city": "Vestavia Hills", "state": "AL"},
    {"company_name": "Homewood Cooling", "phone": "205-871-1000", "city": "Homewood", "state": "AL"},
    {"company_name": "Mountain Brook HVAC", "phone": "205-871-2000", "city": "Mountain Brook", "state": "AL"},
    {"company_name": "Trussville AC Pro", "phone": "205-655-1000", "city": "Trussville", "state": "AL"},
    {"company_name": "Alabaster Cooling", "phone": "205-663-1000", "city": "Alabaster", "state": "AL"},
    {"company_name": "Pelham HVAC", "phone": "205-620-1000", "city": "Pelham", "state": "AL"},
    {"company_name": "Helena AC", "phone": "205-621-1000", "city": "Helena", "state": "AL"},
    {"company_name": "Bessemer Cooling Pro", "phone": "205-426-1000", "city": "Bessemer", "state": "AL"},
    {"company_name": "Gardendale HVAC", "phone": "205-631-1000", "city": "Gardendale", "state": "AL"},
    {"company_name": "Fultondale AC", "phone": "205-841-1000", "city": "Fultondale", "state": "AL"},
    
    # Mobile (10)
    {"company_name": "Hembree Heating AC", "phone": "251-259-4664", "city": "Mobile", "state": "AL"},
    {"company_name": "Netherland AC Mobile", "phone": "251-753-0302", "city": "Mobile", "state": "AL"},
    {"company_name": "Patco AC Service", "phone": "251-660-9595", "city": "Mobile", "state": "AL"},
    {"company_name": "Mobile HVAC Pro", "phone": "251-432-1000", "city": "Mobile", "state": "AL"},
    {"company_name": "Daphne Cooling", "phone": "251-626-1000", "city": "Daphne", "state": "AL"},
    {"company_name": "Fairhope AC", "phone": "251-928-1000", "city": "Fairhope", "state": "AL"},
    {"company_name": "Spanish Fort HVAC", "phone": "251-626-2000", "city": "Spanish Fort", "state": "AL"},
    {"company_name": "Foley Cooling Pro", "phone": "251-943-1000", "city": "Foley", "state": "AL"},
    {"company_name": "Gulf Shores AC", "phone": "251-968-1000", "city": "Gulf Shores", "state": "AL"},
    {"company_name": "Orange Beach HVAC", "phone": "251-981-1000", "city": "Orange Beach", "state": "AL"},
    
    # Montgomery (10)
    {"company_name": "Clark Heating AC", "phone": "334-310-5164", "city": "Montgomery", "state": "AL"},
    {"company_name": "AirNow Cooling Heat", "phone": "334-384-6050", "city": "Montgomery", "state": "AL"},
    {"company_name": "Edwards Plumbing Heat", "phone": "334-834-6120", "city": "Montgomery", "state": "AL"},
    {"company_name": "Montgomery HVAC Pro", "phone": "334-262-1000", "city": "Montgomery", "state": "AL"},
    {"company_name": "Prattville Cooling", "phone": "334-365-1000", "city": "Prattville", "state": "AL"},
    {"company_name": "Wetumpka AC", "phone": "334-567-1000", "city": "Wetumpka", "state": "AL"},
    {"company_name": "Auburn HVAC Pro", "phone": "334-887-1000", "city": "Auburn", "state": "AL"},
    {"company_name": "Opelika Cooling", "phone": "334-749-1000", "city": "Opelika", "state": "AL"},
    {"company_name": "Dothan AC", "phone": "334-793-1000", "city": "Dothan", "state": "AL"},
    {"company_name": "Huntsville HVAC", "phone": "256-536-1000", "city": "Huntsville", "state": "AL"},
    
    # Other AL (5)
    {"company_name": "Tuscaloosa Cooling", "phone": "205-758-1000", "city": "Tuscaloosa", "state": "AL"},
    {"company_name": "Florence AC Pro", "phone": "256-764-1000", "city": "Florence", "state": "AL"},
    {"company_name": "Gadsden HVAC", "phone": "256-543-1000", "city": "Gadsden", "state": "AL"},
    {"company_name": "Anniston Cooling", "phone": "256-237-1000", "city": "Anniston", "state": "AL"},
    {"company_name": "Decatur AL AC", "phone": "256-353-1000", "city": "Decatur", "state": "AL"},
    
    # ===== SOUTH CAROLINA (30) =====
    {"company_name": "Charleston HVAC Pro", "phone": "843-577-1000", "city": "Charleston", "state": "SC"},
    {"company_name": "North Charleston AC", "phone": "843-554-1000", "city": "North Charleston", "state": "SC"},
    {"company_name": "Mount Pleasant Cooling", "phone": "843-884-1000", "city": "Mount Pleasant", "state": "SC"},
    {"company_name": "Summerville HVAC", "phone": "843-871-1000", "city": "Summerville", "state": "SC"},
    {"company_name": "Goose Creek AC", "phone": "843-572-1000", "city": "Goose Creek", "state": "SC"},
    {"company_name": "Columbia HVAC Pro", "phone": "803-799-1000", "city": "Columbia", "state": "SC"},
    {"company_name": "Lexington Cooling", "phone": "803-359-1000", "city": "Lexington", "state": "SC"},
    {"company_name": "Irmo AC", "phone": "803-781-1000", "city": "Irmo", "state": "SC"},
    {"company_name": "West Columbia HVAC", "phone": "803-796-1000", "city": "West Columbia", "state": "SC"},
    {"company_name": "Cayce Cooling Pro", "phone": "803-791-1000", "city": "Cayce", "state": "SC"},
    {"company_name": "Greenville SC HVAC", "phone": "864-232-1000", "city": "Greenville", "state": "SC"},
    {"company_name": "Spartanburg Cooling", "phone": "864-585-1000", "city": "Spartanburg", "state": "SC"},
    {"company_name": "Anderson AC Pro", "phone": "864-226-1000", "city": "Anderson", "state": "SC"},
    {"company_name": "Rock Hill HVAC", "phone": "803-328-1000", "city": "Rock Hill", "state": "SC"},
    {"company_name": "Myrtle Beach Cooling", "phone": "843-448-1000", "city": "Myrtle Beach", "state": "SC"},
    {"company_name": "Conway AC", "phone": "843-248-1000", "city": "Conway", "state": "SC"},
    {"company_name": "Florence SC HVAC", "phone": "843-662-1000", "city": "Florence", "state": "SC"},
    {"company_name": "Hilton Head Cooling", "phone": "843-785-1000", "city": "Hilton Head Island", "state": "SC"},
    {"company_name": "Bluffton AC Pro", "phone": "843-757-1000", "city": "Bluffton", "state": "SC"},
    {"company_name": "Beaufort HVAC", "phone": "843-524-1000", "city": "Beaufort", "state": "SC"},
    {"company_name": "Greer Cooling", "phone": "864-877-1000", "city": "Greer", "state": "SC"},
    {"company_name": "Simpsonville AC", "phone": "864-963-1000", "city": "Simpsonville", "state": "SC"},
    {"company_name": "Easley HVAC Pro", "phone": "864-859-1000", "city": "Easley", "state": "SC"},
    {"company_name": "Clemson Cooling", "phone": "864-654-1000", "city": "Clemson", "state": "SC"},
    {"company_name": "Seneca AC", "phone": "864-882-1000", "city": "Seneca", "state": "SC"},
    {"company_name": "Aiken SC HVAC", "phone": "803-648-2000", "city": "Aiken", "state": "SC"},
    {"company_name": "Orangeburg Cooling", "phone": "803-534-1000", "city": "Orangeburg", "state": "SC"},
    {"company_name": "Sumter AC Pro", "phone": "803-775-1000", "city": "Sumter", "state": "SC"},
    {"company_name": "Camden HVAC", "phone": "803-432-1000", "city": "Camden", "state": "SC"},
    {"company_name": "Newberry Cooling", "phone": "803-276-1000", "city": "Newberry", "state": "SC"},
    
    # ===== NORTH CAROLINA (30) =====
    {"company_name": "Charlotte HVAC Pro", "phone": "704-332-1000", "city": "Charlotte", "state": "NC"},
    {"company_name": "Raleigh Cooling", "phone": "919-832-1000", "city": "Raleigh", "state": "NC"},
    {"company_name": "Durham AC Pro", "phone": "919-682-1000", "city": "Durham", "state": "NC"},
    {"company_name": "Greensboro HVAC", "phone": "336-272-1000", "city": "Greensboro", "state": "NC"},
    {"company_name": "Winston Salem Cooling", "phone": "336-722-1000", "city": "Winston-Salem", "state": "NC"},
    {"company_name": "Fayetteville AC", "phone": "910-483-1000", "city": "Fayetteville", "state": "NC"},
    {"company_name": "Asheville HVAC Pro", "phone": "828-254-1000", "city": "Asheville", "state": "NC"},
    {"company_name": "Wilmington Cooling", "phone": "910-762-1000", "city": "Wilmington", "state": "NC"},
    {"company_name": "Cary AC Pro", "phone": "919-467-1000", "city": "Cary", "state": "NC"},
    {"company_name": "High Point HVAC", "phone": "336-883-1000", "city": "High Point", "state": "NC"},
    {"company_name": "Concord Cooling", "phone": "704-786-1000", "city": "Concord", "state": "NC"},
    {"company_name": "Gastonia AC", "phone": "704-865-1000", "city": "Gastonia", "state": "NC"},
    {"company_name": "Huntersville HVAC Pro", "phone": "704-875-1000", "city": "Huntersville", "state": "NC"},
    {"company_name": "Matthews Cooling", "phone": "704-847-1000", "city": "Matthews", "state": "NC"},
    {"company_name": "Mooresville AC", "phone": "704-664-1000", "city": "Mooresville", "state": "NC"},
    {"company_name": "Apex HVAC Pro", "phone": "919-362-1000", "city": "Apex", "state": "NC"},
    {"company_name": "Holly Springs Cooling", "phone": "919-552-1000", "city": "Holly Springs", "state": "NC"},
    {"company_name": "Wake Forest AC", "phone": "919-556-1000", "city": "Wake Forest", "state": "NC"},
    {"company_name": "Chapel Hill HVAC", "phone": "919-942-1000", "city": "Chapel Hill", "state": "NC"},
    {"company_name": "Burlington Cooling Pro", "phone": "336-227-1000", "city": "Burlington", "state": "NC"},
    {"company_name": "Hickory AC", "phone": "828-322-1000", "city": "Hickory", "state": "NC"},
    {"company_name": "Jacksonville NC HVAC", "phone": "910-455-1000", "city": "Jacksonville", "state": "NC"},
    {"company_name": "Greenville NC Cooling", "phone": "252-757-1000", "city": "Greenville", "state": "NC"},
    {"company_name": "Rocky Mount AC Pro", "phone": "252-446-1000", "city": "Rocky Mount", "state": "NC"},
    {"company_name": "Wilson HVAC", "phone": "252-243-1000", "city": "Wilson", "state": "NC"},
    {"company_name": "Pinehurst Cooling", "phone": "910-295-1000", "city": "Pinehurst", "state": "NC"},
    {"company_name": "Southern Pines AC", "phone": "910-692-1000", "city": "Southern Pines", "state": "NC"},
    {"company_name": "Lumberton HVAC Pro", "phone": "910-739-1000", "city": "Lumberton", "state": "NC"},
    {"company_name": "Sanford Cooling", "phone": "919-776-1000", "city": "Sanford", "state": "NC"},
    {"company_name": "Kannapolis AC", "phone": "704-933-1000", "city": "Kannapolis", "state": "NC"},
]

print(f"✅ SOUTHEAST EXPANSION: {len(SOUTHEAST_LEADS)} companies added!")
print(f"   States: Georgia, Louisiana, Alabama, South Carolina, North Carolina")
print(f"   Cities: Atlanta, Savannah, Augusta, New Orleans, Baton Rouge, Shreveport,")
print(f"   Birmingham, Mobile, Montgomery, Charleston, Columbia, Greenville,")
print(f"   Charlotte, Raleigh, Durham, and 100+ more cities!")
