-- SUPABASE SQL HANDOVER PROTOCOL
-- Copy and Paste this entire block into your Supabase SQL Editor to initialize the database.
-- 1. Create LEADS Table
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    email TEXT,
    phone TEXT,
    name TEXT,
    source TEXT,
    metadata TEXT
);
-- 2. Create INTERACTIONS Table (For Voice Logs)
CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    type TEXT,
    summary TEXT,
    transcript TEXT,
    lead_phone TEXT
);
-- 3. (Optional) Row Level Security - Enable Public Read for Dashboard (If using client-side fetch)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Access" ON leads FOR
SELECT USING (true);
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Access" ON interactions FOR
SELECT USING (true);
-- 4. Initial Seed Data (To verify connection)
INSERT INTO leads (name, email, source)
VALUES (
        'Supabase Connected',
        'db@verified.ai',
        'MIGRATION_SUCCESS'
    );