import streamlit as st
import pandas as pd
import supabase
import folium
from streamlit_folium import st_folium
import os
import json

# --- CONFIG ---
# Auto-detect from environment or use placeholders
SUPABASE_URL = os.environ.get("SUPABASE_URL", "<your-supabase-url>")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "<your-supabase-key>")

st.set_page_config(page_title="Warlord Dashboard", layout="wide", page_icon="⚔️")

# --- SUPABASE ---
@st.cache_resource
def get_supabase():
    try:
        return supabase.create_client(SUPABASE_URL, SUPABASE_KEY)
    except Exception as e:
        st.error(f"Failed to initialize Supabase client: {e}")
        return None

sb = get_supabase()

# --- TITLE ---
st.title("⚔️ The Warlord Dashboard")
st.markdown("**Mission 24:** Visualizing the Theater of Operations (Florida Sector).")

# --- DATA FETCH ---
@st.cache_data(ttl=600)
def fetch_leads():
    if not sb:
        return pd.DataFrame()
    
    try:
        # Fetch all contacts from contacts_master
        response = sb.table("contacts_master").select("*").execute()
        df = pd.DataFrame(response.data)
        return df
    except Exception as e:
        st.error(f"Error fetching data: {e}")
        return pd.DataFrame()

df = fetch_leads()

# --- METRICS ---
if not df.empty:
    total_leads = len(df)
    # Check for 'status' column case-insensitively
    if 'status' in df.columns:
        nurtured = len(df[df['status'].astype(str).str.contains('nurtured', case=False, na=False)])
        booked = len(df[df['status'].astype(str).str.contains('booked', case=False, na=False)])
    else:
        nurtured = 0
        booked = 0
        
    revenue_opp = total_leads * 2000 # Estimate $2k per lead lifetime value
    
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Targets", total_leads)
    c2.metric("Nurtured", nurtured)
    c3.metric("Booked", booked)
    c4.metric("Revenue Opportunity", f"${revenue_opp:,.0f}")
else:
    st.warning("No data found in 'contacts_master'. Ensure the Scout Agent has run.")

# --- MAP ---
st.subheader("🗺️ Tactical Map")

if not df.empty:
    # Basic Filtering
    if 'status' in df.columns:
        status_filter = st.multiselect("Filter by Status", df['status'].unique())
        dff = df.copy()
        if status_filter:
            dff = dff[dff['status'].isin(status_filter)]
    else:
        dff = df.copy()
    
    # Coordinates Logic 
    # Check for latitude/longitude columns. If missing, we can't plot.
    if 'latitude' in dff.columns and 'longitude' in dff.columns:
        # Filter out rows with missing coords
        dff = dff.dropna(subset=['latitude', 'longitude'])
        
        if not dff.empty:
            # Center map on average of points, or default to Central FL
            avg_lat = dff['latitude'].mean()
            avg_lon = dff['longitude'].mean()
            m = folium.Map(location=[avg_lat, avg_lon], zoom_start=9, tiles="CartoDB dark_matter")
            
            for idx, row in dff.iterrows():
                lat = row['latitude']
                lon = row['longitude']
                
                # Color Coding
                status = str(row.get('status', '')).lower()
                color = 'red' # Default: New Lead
                if 'nurtured' in status or 'contacted' in status:
                    color = 'yellow'
                if 'booked' in status or 'sold' in status:
                    color = 'green'
                    
                tooltip_txt = f"<b>{row.get('company_name', 'Unknown')}</b><br>Status: {row.get('status', 'N/A')}<br>City: {row.get('city', 'N/A')}"
                
                # Popup with more info
                popup_html = f"""
                <div style="width:200px">
                    <b>{row.get('company_name', 'Unknown')}</b><br>
                    {row.get('city', '')}, {row.get('state', '')}<br>
                    <hr>
                    <i>{row.get('ai_summary', 'No summary.')}</i>
                </div>
                """
                
                folium.Marker(
                    [lat, lon],
                    popup=popup_html,
                    tooltip=tooltip_txt,
                    icon=folium.Icon(color=color, icon="info-sign")
                ).add_to(m)
            
            st_folium(m, width=1400, height=600)
        else:
            st.warning("Leads found, but no valid coordinates available to plot.")
    else:
        st.warning("Dataset missing 'latitude' or 'longitude' columns.")

# --- DATA TABLE ---
st.subheader("📋 Reconnaissance Data")
if not df.empty:
    st.dataframe(df)

# --- FOOTER ---
st.markdown("---")
st.caption("Auto-Generated by Sovereign Architect Agent.")
