"""
AEO Webhook Test Server
Local Flask endpoint to simulate the payment webhook and generate audits.
Run with: python execution/aeo_webhook_test.py
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import json
import random
import datetime
import sys
import os

# Add parent directory for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

app = Flask(__name__)
CORS(app)  # Enable CORS for local testing

@app.route('/generate-audit', methods=['POST'])
def generate_audit():
    """
    Receives form data and generates an AEO audit report.
    """
    try:
        data = request.get_json()
        
        name = data.get('name', 'Customer')
        email = data.get('email', '')
        website = data.get('website', 'example.com')
        niche = data.get('niche', 'Business')
        
        # Generate metrics
        ai_search_pct = random.randint(1, 8)
        direct_pct = random.randint(50, 70)
        status = 'INVISIBLE' if ai_search_pct < 10 else 'LOW VISIBILITY'
        revenue_ranges = ['$1M - $5M', '$5M - $10M', 'Under $1M']
        est_revenue = random.choice(revenue_ranges)
        
        # Generate competitors
        competitors = [
            {'name': 'LocalPro Solutions', 'ai_rank': 1},
            {'name': 'Metro Service Experts', 'ai_rank': 2},
            {'name': f'Premier {niche} Co', 'ai_rank': 3}
        ]
        
        # Build the report
        report = f"""# AI VISIBILITY AUDIT: {website}

**Date:** {datetime.date.today().isoformat()}
**Prepared For:** {name}
**Target Niche:** {niche}
**Est. Revenue Range:** {est_revenue}

---

## 1. Executive Summary: The "AI Gap"

**Current Status: {status}**

Your business is currently **{status}** in AI search recommendations (ChatGPT, Gemini, Perplexity).

While your direct traffic appears strong ({direct_pct}%), this means you are only reaching people who **already know your name**. You are missing the growing segment of buyers who search through AI assistants.

**AI Search Traffic:** {ai_search_pct}% (Industry leaders average 15-25%)

---

## 2. Competitive AI Ranking

When users ask AI assistants for "Best {niche} near me," here's who gets recommended:

| Rank | Competitor | Why They Rank |
|------|------------|---------------|
| #1 | {competitors[0]['name']} | Strong schema markup, 200+ reviews |
| #2 | {competitors[1]['name']} | Active press mentions, NAP consistent |
| #3 | {competitors[2]['name']} | FAQ pages match AI query patterns |
| ... | **{website}** | [NOT FOUND IN AI RECOMMENDATIONS] |

---

## 3. Revenue Impact Analysis

Based on your industry and traffic profile:

- **Estimated Monthly AI Traffic Lost:** 150-300 visitors
- **Average Lead Value ({niche}):** $200-500
- **Annual Revenue Leak:** $18,000 - $72,000

---

## 4. The 3-Step "Empire" Fix

### Pillar 1: Local Authority Foundation
- [ ] Sync Google Business Profile with website NAP
- [ ] Implement review generation workflow
- [ ] Add LocalBusiness schema markup

### Pillar 2: Semantic Content Structure  
- [ ] Rewrite service pages with natural language Q&A
- [ ] Add FAQ schema to all key pages
- [ ] Create location-specific landing pages

### Pillar 3: Sentiment Siege
- [ ] Distribute 3 press releases over 90 days
- [ ] Secure mentions on 5 local authority sites
- [ ] Build citation consistency across directories

---

## 5. Next Steps

Book a **free 15-minute strategy call** to walk through this audit and get your custom AEO roadmap:

**[Book Your Call](https://link.aiserviceco.com/discovery)**

---

*Generated by Empire Unified AI - AI Service Co*
"""
        
        result = {
            'success': True,
            'customer': {
                'name': name,
                'email': email,
                'website': website,
                'niche': niche
            },
            'report': report,
            'status': status,
            'metrics': {
                'ai_search_pct': ai_search_pct,
                'direct_pct': direct_pct,
                'est_revenue': est_revenue
            }
        }
        
        print(f"[AEO] Generated audit for {website} ({niche})")
        return jsonify(result)
        
    except Exception as e:
        print(f"[AEO] Error: {str(e)}")
        return jsonify({'success': False, 'error': str(e)}), 500


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint."""
    return jsonify({'status': 'ok', 'service': 'aeo-webhook-test'})


if __name__ == '__main__':
    print("=" * 50)
    print("AEO Webhook Test Server")
    print("=" * 50)
    print("Endpoints:")
    print("  POST http://localhost:5000/generate-audit")
    print("  GET  http://localhost:5000/health")
    print("=" * 50)
    app.run(host='0.0.0.0', port=5000, debug=True)
