import os
from supabase import create_client, Client

SUPABASE_URL = os.getenv("SUPABASE_URL") or "https://rzcpfwkygdvoshtwxncs.supabase.co"
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Y3Bmd2t5Z2R2b3NodHd4bmNzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjU5MDQyNCwiZXhwIjoyMDgyMTY2NDI0fQ.wiyr_YDDkgtTZfv6sv0FCAmlfGhug81xdX8D6jHpTYo"

def create_log_table():
    print("🛠️ Creating 'brain_logs' table...")
    # Supabase Python client doesn't support 'create table' directly easily via 'rpc' unless we have a function.
    # But we can try to use the raw PostgREST (usually restricted) or just use the dashboard.
    # HOWEVER, we can't use dashboard.
    
    # We will assume we might fail here if we don't have SQL access.
    # BUT, we can use a workaround: we can't really create tables via the JS/Python client unless we have a SQL function exposed.
    
    # Alternative: Use "logs" table if it exists? No.
    
    print("❌ ERROR: Cannot create table via Client. Please use Supabase Dashboard SQL Editor.")
    print("Run this SQL:")
    print("""
    create table public.brain_logs (
      id bigint generated by default as identity primary key,
      created_at timestamp with time zone default timezone('utc'::text, now()) not null,
      message text not null
    );
    alter table public.brain_logs enable row level security;
    create policy "Public Read" on public.brain_logs for select using (true);
    create policy "Service Insert" on public.brain_logs for insert with check (true);
    """)

if __name__ == "__main__":
    create_log_table()
