
import os
import requests
import json
from datetime import datetime

# --- CONFIG ---
BRIDGE_URL = "https://empire-unified-backup-production-6d15.up.railway.app/bridge/performance"
BRIDGE_TOKEN = "sov-audit-2026-ghost"

def get_performance_stats():
    print("🛰️ Connecting to Sovereign Board Bridge...")
    try:
        headers = {"X-Sovereign-Token": BRIDGE_TOKEN}
        res = requests.get(BRIDGE_URL, headers=headers)
        if res.status_code == 200:
            return res.json()
        else:
            print(f"❌ Handshake Failed: {res.status_code}")
            return None
    except Exception as e:
        print(f"❌ Connection Error: {e}")
        return None

def generate_briefing():
    data = get_performance_stats()
    if not data:
        return
        
    print("🧠 Analyzing Lead Data for Closures...")
    
    funnel = data.get("funnel", {})
    recent_touches = data.get("recent_touches", [])
    
    # Logic to find "Most Likely to Close"
    # In this simplified version, we look for leads with 'interested' or 'appointment' tags or high interaction
    # For now, let's look at the actual data received.
    
    # MOCK LOGIC: We'll pull the top interested lead if available, 
    # else we analyze the niches with highest positive responses.
    
    niche_stats = funnel.get("niches", {})
    best_niche = "HVAC"
    max_pos = -1
    for niche, stats in niche_stats.items():
        pos = stats.get("positive", 0)
        if pos > max_pos:
            max_pos = pos
            best_niche = niche
            
    briefing = f"""# 🏛️ SOVEREIGN MORNING BRIEFING
**Date**: {datetime.now().strftime('%Y-%m-%d')}
**System Status**: 🟢 HEALTHY

## 🎯 TOP CLOSURE TARGET
The lead most likely to close today is from the **{best_niche}** sector.

**Analysis**:
- High positive response rate in this niche.
- Recent activity detected in `outbound_touches`.

## 📊 PERFORMANCE SNAPSHOT
- **Total Positive Responses**: {funnel.get('positive_responses', 0)}
- **Outreach Active**: {funnel.get('outreach_active', 0)}
- **Campaign Mode**: ⚡ WORKING

## 🛰️ RECENT BRIDGE TRAFFIC
"""
    for touch in recent_touches[:5]:
        briefing += f"- {touch.get('ts')}: {touch.get('channel')} to {touch.get('contact_id')} ({touch.get('status')})\n"

    briefing += "\n--- \n*Generated by Antigravity v11.6 via Sovereign Bridge*"
    
    # Save to Brain
    path = r"C:\Users\nearm\.gemini\antigravity\brain\0b97dae9-c5c0-4924-8d97-793b59319985\morning_briefing.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(briefing)
        
    print(f"\n✅ Briefing Generated at: {path}")
    return path

if __name__ == "__main__":
    generate_briefing()
