FROM python:3.11-slim

WORKDIR /app

COPY gcp_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY gcp_backup_app.py app.py

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app
