import os
import json
from datetime import datetime, timezone
from modules.database.supabase_client import get_supabase

def generate_candidate_dossier(lead_id, candidates=None):
    """
    Generates a professional candidate dossier for a client based on Manus data.
    If candidates are provided, it packages those. Otherwise, it pulls from lead meta.
    """
    supabase = get_supabase()
    if not supabase:
        return {"error": "supabase_auth_failed"}

    try:
        # 1. Look up lead data
        res = supabase.table("contacts_master").select("*").eq("id", lead_id).single().execute()
        lead = res.data
        if not lead:
            return {"error": "lead_not_found"}

        # 2. Extract manus meta
        raw = json.loads(lead.get("raw_research") or "{}")
        manus_meta = raw.get("manus_meta", {})
        
        # 3. Use provided candidates or fallback to meta
        source_candidates = candidates or manus_meta.get("top_candidates", [])
        
        if not source_candidates:
            # Mock candidates if none exist for demo purposes
            source_candidates = [
                {"name": "Sarah Miller", "match_score": 94, "experience": "5 yrs Admin", "notes": "Highly organized, former dental receptionist."},
                {"name": "Marcus Chen", "match_score": 88, "experience": "3 yrs CX", "notes": "Bilingual, tech-savvy, strong phone presence."},
                {"name": "Elena Rodriguez", "match_score": 85, "experience": "2 yrs Retail", "notes": "Cheerful, local to Lakeland, quick learner."}
            ]

        # 4. Generate Markdown/HTML Dossier
        dossier_content = f"""# 📋 Candidate Dossier: {lead.get('company_name')}
**Generated by AI Service Co. Recruitment Engine**
**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}

---

## 🔝 Top 3 AI-Vetted Candidates

"""
        for i, c in enumerate(source_candidates[:3], 1):
            dossier_content += f"""### {i}. {c['name']}
- **Match Score:** {c['match_score']}%
- **Core Experience:** {c['experience']}
- **AI Specialist Note:** {c['notes']}

"""

        dossier_content += """---
**Next Step:** Reply with "INTERVIEW [Number]" to have Maya schedule a 15-min screening call with any of these candidates.
"""

        # 5. Persist Dossier Path
        dossier_filename = f"dossier_{lead_id}.md"
        # In a real system, we'd save this to a bucket. For now, we store in metadata.
        raw["last_dossier"] = dossier_content
        supabase.table("contacts_master").update({"raw_research": json.dumps(raw)}).eq("id", lead_id).execute()

        print(f"✅ Generated dossier for {lead.get('company_name')} ({lead_id})")
        return {"status": "success", "dossier": dossier_content}

    except Exception as e:
        print(f"❌ Dossier Generation Error: {e}")
        return {"status": "error", "error": str(e)}

if __name__ == "__main__":
    # Test for a specific lead if needed
    pass
