-- OP-ABSOLUTE-THRUST: CONSENT DEFENSE LAYER
-- Execute this in the Supabase SQL Editor
CREATE TABLE IF NOT EXISTS consent_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    lead_id TEXT,
    -- GHL Contact ID
    email TEXT,
    phone TEXT,
    consent_type TEXT DEFAULT 'email_only',
    -- email_only, sms_call_verified
    source_url TEXT,
    ip_address TEXT,
    timestamp_verified TIMESTAMP WITH TIME ZONE,
    raw_consent_data JSONB
);
-- Index for fast lookup during outreach
CREATE INDEX IF NOT EXISTS idx_consent_lead_id ON consent_audit_log(lead_id);
CREATE INDEX IF NOT EXISTS idx_consent_phone ON consent_audit_log(phone);
-- Default system state for campaign mode (Reset to 'working' after audit)
UPDATE system_state
SET status = 'working'
WHERE key = 'campaign_mode';